# Stages
# Stage-1:
  # Task-1: Build Docker Image and push to Azure Container Registry ACR
  # Task-2: Copy kube-manifest files to Build Artifact Directory
  # Task-3: Publish build articats to Azure Pipelines
# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3 

trigger:
- master

stages:
- stage: Build
  displayName: 'Build Pipeline'
  jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        repository: 'sharatimage'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        containerRegistry: "myacr"
    
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true

    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'